### ISSUE TITLE
New messages for 4.3

### ISSUE THREAD

**Issue by cameronmcefee** [guideguide/messages#18]
Hello @guideguide/translation! GuideGuide 4.3 has a bunch of new features and some new messages to go along with them. I've also added a few messages that were not previously being translated.

I changed the process again (sorry). It's similar to before, but the file lives in this repo now so I can make it open source. All translations go in:

https://github.com/guideguide/messages/blob/master/src/messages.coffee

To see what needs an update from you, please search that document for `# TODO:` Due to the amount and breadth of the changes in this version, I'll have it in beta for a while. I'm hoping to ship the update some time before the end of March.

:heart: Thank you as always for your help!

**Comment by cameronmcefee** [comment]
I've also given you write access so there will be no need to fork the repo

**Comment by damienbigot** [comment]
French translation updated!

**Comment by cameronmcefee** [comment]
Checking back in, @bomberstudios and @thiagotomasi , if you'd like to include translations for the new features in this release.

Thanks again @damienbigot, yours are now updated in the codebase.
